defaults:
  - msc

total_steps: 100000 # 10000000

rollout_steps: 256 # 1024
update_epochs: 5 # 10

learning_rate: 0.00001

batch_size: 64

clip_ratio: 0.2
value_coefficient: 0.5
entropy_coefficient: 0.0

gamma: 1.0
gae_lambda: 0.95
max_grad_norm: 0.5