"""Expert policy derived from PDNAR's already-stored exact ILP solution."""

from __future__ import annotations

import torch


class ILPExpert:
    """Uniformly chooses any not-yet-selected set in an optimal cover.

    ``primal_optimal_solution`` is generated by PDNAR's set-cover dataset
    builder, so the BC baseline keeps the same optimum labels as PDNAR.
    """

    def __init__(self, data, device: torch.device | str = "cpu"):
        self.solution = data.primal_optimal_solution.to(device).bool().flatten()

    def distribution(self, env, state=None) -> torch.Tensor:
        state = env.state if state is None else state
        eligible = self.solution & ~state.selected
        if not bool(eligible.any()):
            raise RuntimeError("Expert requested after its optimal solution is exhausted.")
        return eligible.float() / eligible.sum()

    def sample_action(self, env, state=None) -> int:
        return int(torch.multinomial(self.distribution(env, state), 1).item())
